### ISSUE TITLE
Enabling and testing phonon-mpv

### ISSUE THREAD

**Issue by jocrecre** [OpenProgger/phonon-mpv#10]
I have the following backends installed: 

user@bionic:/$ ls -lht /usr/lib/x86_64-linux-gnu/qt5/plugins/phonon4qt5_backend/
total 1,3M
-rw-r--r-- 1 root root 491K jul  4 11:46 phonon_mpv.so
-rw-r--r-- 1 root root 359K feb 28  2018 phonon_vlc.so
-rw-r--r-- 1 root root 382K may 18  2016 phonon_gstreamer.so

And I am using the Qt5 video player example: 
https://doc.qt.io/qt-5/qtmultimedia-multimediawidgets-player-example.html

But I cannot play any video, I get a message saying that there is no decoder for audio and no video can be played.

**Comment by zkvsky** [comment]
@jocrecre is this player using phonon even?

**Comment by jocrecre** [comment]
I guess so, as I understand it works like this:

    app > Qt > phonon > phonon-backend > mpv/vlc/gstreamer

But if you can tell me any other app using the backend it will be appreciated.

**Comment by zkvsky** [comment]
@jocrecre I'm not certain that phonon is mandatory for all Qt apps, I might be wrong, ones which for sure use it are: Kaffeine and Dragon player

**Comment by jocrecre** [comment]
Thanks for the answer. 
I have just checked both (Kaffeine and Dragon). Kaffeine seems to use vlc engine even it the /usr/lib/x86_64-linux-gnu/qt5/plugins/phonon4qt5_backend/phonon_vlc.so has been removed. I can confirm that Dragon uses /usr/lib/x86_64-linux-gnu/qt5/plugins/phonon4qt5_backend/phonon_mpv.so and it works playing videos. Indeed Dragon is a Qt5.9.5 based app so I will try to analyse it and see what is happening whith the Qt video example I mentioned.

**Comment by zkvsky** [comment]
@jocrecre Just checked some recent commits of Kaffeine and it seems that they're using libVLC directly not phonon
Edit.  [Amarok and Juk use phonon too]
After some reading; phonon is no longer a part of Qt [it's part of kde], it was in 4.x series, that explains why your example isn't working

**Comment by jocrecre** [comment]
So, why is Dragon working with phonon_mpv.so? 
Its true that Qt does not mention [phonon](https://wiki.qt.io/Qt_Multimedia_Backends) as a backend it does mention gstreamer, but ubuntu is packaging the phonon5qt4-backend-vlc/gstreamer , I cannot undertand it.

**Comment by zkvsky** [comment]
Phonon is just an abstraction, mainly used by kde so they don't have to care about multimedia subsystem eg. when their apps run under mac or windows. Qt apps don't have to use phonon [especially now that they have their own subsystem qtmultimedia ] they can use backends directly [ gstreamer, vlc, mpv, you name it ] it's a choice of developer. There's not much reason to unless it's kde tied app like Dragon. 
Think about phonon as part of kde, not Qt. Qt and pure Qt apps [not tied to kde ] don't need it.

**Comment by zkvsky** [comment]
@jocrecre Anyway, why do you wan't to use phonon-mpv?
If you want more info about this whole mess check [here](https://colin.guthr.ie/2010/05/qt-multimediamobility-vs-phonon-fight/), first comment under for tldr

**Comment by jocrecre** [comment]
I have always used phonon-vlc for qt4 apps and the performance has been always good enough. Now I am facing some hw decoding issues using VLC with an ARM chipset that seems to be solved with mpv so that I just wanted to give it a try. Finally I have realised that Qt5 is not supporting phonon anymore and they are focussed in gstreamer engine, although I have some doubts since Dragon is a Qt5 based app and it uses phonon, and there is also a suit of phonon4qt5-backend-vlc/gstreamer/mpv. As you can see I am not clear at all but I will try facing it. 

Why do you ask for it? Thanks anyway.

**Comment by zkvsky** [comment]
Dragon is Qt5 but it's also KDE app, same as Juk, and whole plasma desktop, and they  [ KDE folks ] decided to use/stick with phonon [ which is separate from Qt now, its a part of KDE not Qt ].  
I'm trying to understand why are you trying to use phonon at all, you might not need it, if you want use mpv and have decent decoding just use mpv player or player that uses mpv, no need for phonon

**Comment by OpenProgger** [comment]
Qt5Multimedia only uses gstreamer as backend on Linux and have no connections to phonon. Currently only KDE Applications(which Kaffeine is NOT part of it) and some 3rd party players who mention this explicit support phonon and this backend. If you want to use Qt5 and mpv on a ARM device, have a look at players like smplayer. Or if you want to write a player on your own, look at the libmpv API and their qt5 examples. SInce it's not a problem of the backend, I'm closing it.
