### ISSUE TITLE
Session does not start: ksmserver could not start

### ISSUE THREAD

**Issue by kupiqu** [OpenProgger/phonon-mpv#2]
If I configure phonon to use phonon-mpv, then after loging out, my session does not start anymore. I need to manually delete the ~/.config/kde.org/libphonon.conf file to be able to do so.

Not sure this is happening since I updated my system to Qt 5.12 or that's unrelated to that, since I moved to Qt 5.12 and started to use phonon-mpv by the same time.

**Comment by OpenProgger** [comment]
Plasma 5.14 is currently based on Qt 5.11, so you could be right. Does the other phonon backends work?

**Comment by kupiqu** [comment]
Yes, the default in my system is gstreamer and works with no problem. I wish I could use yours though. 

Btw, I use KDE neon User Edition, which just moved to Qt 5.12

**Comment by OpenProgger** [comment]
Does the session(or ksmserver) simplay crash, so you return to display manager or does the loading hang?
Does the issue appear only on relogin or also after reboot with mpv backend enabled in the settings?
If I get the time, I could try to setup a VM to reproduce the issue.

**Comment by kupiqu** [comment]
> Does the session(or ksmserver) simplay crash, so you return to display manager or does the loading hang?

weirdly enough, sometimes it returns to sddm and sometimes stacks showing a pop-up error like the following I found on the internet:

![image](https://user-images.githubusercontent.com/3875196/52514038-9b4fab80-2bdc-11e9-9d2d-5d11c9c68d02.png)


> Does the issue appear only on relogin or also after reboot with mpv backend enabled in the settings?

unfortunately it happens both ways

> If I get the time, I could try to setup a VM to reproduce the issue.

Sounds great!

**Comment by zkvsky** [comment]
I'm currently on QT version 5.12.1 and have no such issues

**Comment by kupiqu** [comment]
My system is in Qt 5.12.0, I hope it is a Qt issue that gets fixed when KDE neon moves to 5.12.1, but perhaps there are more things behind the scenes here :/

**Comment by ahjolinna** [comment]
I don't have this problem on openSUSE tumbleweed, and is still using Qt 5.12.0..for some reason even when its a rolling distro..hmm

```
inxi -Sxx
System:    Host: linux Kernel: 4.20.10-1-default x86_64 bits: 64 compiler: gcc v: 8.2.1 Desktop: KDE Plasma 5.15.0 
           tk: Qt 5.12.0 wm: kwin_x11 dm: SDDM Distro: openSUSE Tumbleweed 20190220
```

**Comment by OpenProgger** [comment]
Compiled current master on a KDE Neon stable image from last week with current mpv.
Session starts without issues and dragon player works too.
hwdec is untested because QEMU doesn't support vaapi passthrough but thats not the issue.
Is this issue still present with recent updates?

**Comment by kupiqu** [comment]
> Compiled current master on a KDE Neon stable image from last week with current mpv.
> Session starts without issues and dragon player works too.
> hwdec is untested because QEMU doesn't support vaapi passthrough but thats not the issue.
> Is this issue still present with recent updates?

Excellent! It may very well be that this got fixed with the changes that you have recently introduced. I've just tested this with a brand new user and worked! I hope to confirm the same behavior with my user account once I restart my session :)

**Comment by kupiqu** [comment]
Unfortunately it didn't work. It must be an interaction of phonon-mpv with some other configuration (sth else in ~/.config). It failed for my user and also for the new one once I synchronized the config folder.

I'll try to find it out but I'm kind of tired and out of ideas at the moment. If you don't mind I'll leave this open for the case someone else encounters the issue and can help to narrow down the other factor playing a role in the "party"...

**Comment by OpenProgger** [comment]
Since this issue is stale for long time without any additional info for reproduction, I will close it with the recent Plasma 6 release. If this problem persists a new issue with fresh logs can be created.
