### ISSUE TITLE
need help with openSUSE build

### ISSUE THREAD

**Issue by ahjolinna** [OpenProgger/phonon-mpv#3]
I just found your project from aur and I was going to add it to my openSUSE repo, but currently it wont build. I get this error: 
```
[   99s] /home/abuild/rpmbuild/BUILD/phonon-mpv-0.0.5.0.ffcffc4/src/video/videowidget.cpp:33:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
[   99s]  #include <qpa/qplatformnativeinterface.h>
[   99s]           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   99s] compilation terminated.
```

[here is the full log link](https://pastebin.com/raw/uQCV0UJk)

there could be a depends issue also, here is the [my repo](https://build.opensuse.org/package/show/home:ahjolinna/phonon-backend-mpv)

PS. thanks for making this <3

**Comment by OpenProgger** [comment]
Your system is missing of the internal headers of QtGui.
I don't know how the package on openSUSE is called but watch out for a package name like qtgui-private, qtgui-private-dev or libqtgui-private-headers which provides the missing file.

**Comment by ahjolinna** [comment]
okay it was `libQt5Gui-private-headers-devel`, but now I get this :D 
```
fvisibility-inlines-hidden   -fPIC -std=gnu++11 -o CMakeFiles/phonon_mpv.dir/utils/debug.cpp.o -c /home/abuild/rpmbuild/BUILD/phonon-mpv-0.0.5.0.ffcffc4/src/utils/debug.cpp
[  173s] /home/abuild/rpmbuild/BUILD/phonon-mpv-0.0.5.0.ffcffc4/src/video/videowidget.cpp:37:10: fatal error: mpv/render_gl.h: No such file or directory
[  173s]  #include <mpv/render_gl.h>
[  173s]           ^~~~~~~~~~~~~~~~~
[  173s] compilation terminated.
[  173s] make[2]: *** [src/CMakeFiles/phonon_mpv.dir/build.make:282: src/CMakeFiles/phonon_mpv.dir/video/videowidget.cpp.o] Error 1
[  173s] make[2]: *** Waiting for unfinished jobs....
```

**Comment by OpenProgger** [comment]
Now the headers from libmpv are missing and/or your mpv installation is too old. The render API is available since 0.29 I think.

**Comment by ahjolinna** [comment]
apparently I forgot to add mpv -devel version...sigh

**Comment by jocrecre** [comment]
I have tried to pass the cmake but it fails, I get the following error:

user@bionic:/tmp/phonon-mpv/build$ cmake -DCMAKE_INSTALL_PREFIX=/usr ../src/
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:3 (add_definitions):
  Policy CMP0005 is not set: Preprocessor definition values are now escaped
  automatically.  Run "cmake --help-policy CMP0005" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:5 (if):
  if given arguments:

    "VERSION_GREATER" "4.9.50"

  Unknown arguments specified


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/tmp/phonon-mpv/build/CMakeFiles/CMakeOutput.log".
