### ISSUE TITLE
blackscreen in gwenview when use vulkan as output 

### ISSUE THREAD

**Issue by sl1pkn07** [OpenProgger/phonon-mpv#4]
Hi

i have enable the vulkan output in my mpv player, then if use phonon-mpv in gwenview and try to watch a video,  obtain a blackscren in the app. the audio plays fine

is possible use phonon-mpv in gwenview (or other kde app with phonon support) with vulkan output?

kde 5.15.3/5.56.0
Qt 5.12.2 
phonon 4.10.2
mpv  0.29.0

greetings

**Comment by OpenProgger** [comment]
Sadly mpv's client API supports embedded rendering only with opengl :(
As soon as they extend libmpv to render on Vulkan surfaces, I will implement it (Qt supports Vulkan already since 5.10)

**Comment by OpenProgger** [comment]
Long time passed and there seems to be no movement on mpv-side to provide a vulkan rendering backend. This issue can be reopened if something changes on their side.

**Comment by zkvsky** [comment]
> Long time passed and there seems to be no movement on mpv-side to provide a vulkan rendering backend. This issue can be reopened if something changes on their side.

MPV fully supports Vulkan output, not only that, there's hwdec vulkan now too, so you can have vulkan only chain [built without vaapi or opengl, egl]
With such config I can play 4K Bluray on my integrated Intel GPU, which otherwise chokes.

config example:
```
gpu-api=vulkan
hwdec=vulkan
gpu-context=waylandvk

```

**Comment by sl1pkn07** [comment]
@barolo see the opened mpv issue

**Comment by zkvsky** [comment]
> @barolo see the opened mpv issue

Ah, thanks, now I get  it.
