### ISSUE TITLE
No video mp4 file in dragon player

### ISSUE THREAD

**Issue by kupiqu** [OpenProgger/phonon-mpv#5]

**Comment by ahjolinna** [comment]
I haven't really seen any videos working with dragon player (with mpv) ...there is just audio playing

**Comment by kupiqu** [comment]
> I haven't really seen any videos working with dragon player (with mpv) ...there is just audio playing

I see. I only tested the mp4 format (dragon player displays the video with gstreamer just fine)

**Comment by OpenProgger** [comment]
I am able to watch mkv/mp4 videos inside dragon player(with hardware acceleration).
What distro are you using and are you using a custom mpv.conf?
For better diagnostics could you run dragon player with PHONON_BACKEND_DEBUG=3(beware, there will be much output) and post your mpv.conf(if you use one).

**Comment by kupiqu** [comment]
I use KDE neon (built on top of Ubuntu LTS).

I played with mpv.conf with different hardware acceleration options. The following one works fine in mpv and smplayer (very low CPU %), but doesn't fix the dragon issue:
```
vo=vaapi
hwdec=vaapi
```
> What distro are you using and are you using a custom mpv.conf?

Interesting. Would you mind sharing your mpv.conf?

I'll try to get the debug info...

**Comment by kupiqu** [comment]
Please see: https://pastebin.com/4mhbigM4

**Comment by OpenProgger** [comment]
I only have the one line in my mpv.conf to enable hardware decoding, nothing more.
I compared your log with mine and I see in your log no information about libmpv itself.
For reference this is my log: [https://pastebin.com/eFBvaZpi](https://pastebin.com/eFBvaZpi)

This could mean:
- your mpv installation is outdated(I doubt it because you compiled it).
- mpv itself is compiled without opengl support or something libmpv related that is needed for the render API.

Another issue #2 had also problems with phonon-mpv under KDE neon.
I tried to set up an KDE neon environment inside of a VM. But the image I used had an outdated mpv version in the repo. I will take the next days to try it again(and compile mpv myself if needed).

**Comment by kupiqu** [comment]
I got mpv from the following ppa repo: https://launchpad.net/~mc3man/+archive/ubuntu/bionic-media

Wondering whether there may be sth wrong with it

**Comment by OpenProgger** [comment]
Thanks for the link, I try to reproduce it the next days.
After a first look I see the libmpv of the ppa is compiled without wayland support, but this could be just related for vaapi support under Plasma Wayland.

**Comment by kupiqu** [comment]
> Thanks for the link, I try to reproduce it the next days.

Great, thanks

> After a first look I see the libmpv of the ppa is compiled without wayland support, but this could be just related for vaapi support under Plasma Wayland.

The issues, this one and #2, happen in X

**Comment by OpenProgger** [comment]
After a closer look in your debug output, I saw that for some reason a invalid mime-type was detected, which disables the video output.
I made some changes now to let mpv decide if it will render something or not.
Pls test the current master and if it still don't work, post the debug log.

**Comment by kupiqu** [comment]
Video is displayed now in Dragon, which is great. Thank you!

Unfortunately though and unlike mpv (or smplayer using mpv), dragon is not using hardware decoding:

```
PHONON-MPV "[vd]Opening decoder h264\n"
PHONON-MPV "[vd]Looking at hwdec h264-vaapi...\n"
PHONON-MPV "[vd]Could not create device.\n"
PHONON-MPV "[vd]No hardware decoding available for this codec.\n"
PHONON-MPV "[vd]Using software decoding.\n"
```

Should we close this and open a second issue specifically about this?

Also, did you have a chance to test #2 ?

**Comment by OpenProgger** [comment]
If you have hwdec set inside of ~/.config/Phonon/mpv.conf it should work. Did you also try with vdpau?
Could you post the logs from a working mpv with working hwdec and the debug from your dragon player into a new issue?

> Also, did you have a chance to test #2 ?

Until it's closed I have an eye on it

**Comment by kupiqu** [comment]
> If you have hwdec set inside of ~/.config/Phonon/mpv.conf it should work.

I have exactly the same settings in both `~/.config/mpv/mpv.conf` and `~/.config/Phonon/mpv.conf`:
```
vo=vaapi
hwdec=vaapi
```

> Did you also try with vdpau?

Didn't, because I thought vaapi is the one for intel graphics like mine, while vdpau is the one for nvidia, but perhaps I'm wrong.

> Could you post the logs from a working mpv with working hwdec and the debug from your dragon player into a new issue?

Sure. Let's continue the discussion there...

>>Also, did you have a chance to test #2 ?

> Until it's closed I have an eye on it

Thank you!

**Comment by OpenProgger** [comment]
> Didn't, because I thought vaapi is the one for intel graphics like mine, while vdpau is the one for nvidia, but perhaps I'm wrong.

No in this case you're right, Intel is vaapi-only.
I need the logs from phonon-mpv and mpv for comparison. It's possible that you hit a known issue about broken hwdec inside libmpv but working with mpv.

**Comment by kupiqu** [comment]
Thanks for the hint!

I fixed the issue by setting `hwdec=auto`. It seems that the right decoder for the mp4 file I test this with is `h264-vaapi`, not just vaapi. While this doesn't affect mpv, it does affect libmpv (which seems to be pickier). 

Another difference is that `h264-vaapi` itself fails in libmpv and it uses `h264-vaapi-copy`, which seems to be less efficient when comparing mpv's % of CPU use, when manually setting hwdec to either one. 

I may report these two minor issues upstream to mpv repo....

**Comment by ahjolinna** [comment]
seem to be working now...kinda, it just wont play/load the file immediately...you need to couple of times (usually it open on the 2nd try)....sometimes it starts and then stops immediately

https://gist.githubusercontent.com/ahjolinna/3e24de5b0e709bd1c9bf4368e63319ec/raw/911a9529e392065e512b9ce241af6ec10f950b49/gistfile1.txt

I use openSUSE tumblweed with my own [git ("full") build of mpv](https://build.opensuse.org/package/show/home:ahjolinna/mpv)

**Comment by OpenProgger** [comment]
The problem is, dragon player creates the video surface only if the backend reports that the input file is a video.
libmpv needs a surface to read and play a video file, there is no option for mpv to "parse-only" the file.
My way is to set the null-device as video surface, until a video file was opened. After that, dragon player creates this surface and pass it to libmpv. To switch the null-device to libmpv_renderer the playback needs to be restarted.
It's possible that this "restart" confuses libmpv on your system. But once the surface is created by dragon player, the playback should work normal(as you said, after 2nd try/restart the file).
If I have the time I could search for better solutions.

btw: your log looks normal, for better debug pls run dragon player with PHONON_BACKEND_DEBUG=3

**Comment by ahjolinna** [comment]
here is the log: https://gist.githubusercontent.com/ahjolinna/ec03eba068ed2646af52a2fcb46d7907/raw/eaad298d429c9a7f4777e82d4d6a94105744e878/gistfile1.txt

**Comment by ahjolinna** [comment]
it seems to have problem to start to play some files or in general...
log 2 https://gist.githubusercontent.com/ahjolinna/8d01d2dee6d390dfa6a21dabd9612f6e/raw/411365739c00507fc2e9caabcb9e91f732a97194/gistfile1.txt

**Comment by ahjolinna** [comment]
it seems if you load 1 file and get it to play/load then others seems to work after that...but not always.
https://gist.githubusercontent.com/ahjolinna/2e27547265cc9aaf5aac41c3273ce8fa/raw/1deae15d06df87dadc1cfc44b8dd13cb572fd693/gistfile1.txt

**Comment by OpenProgger** [comment]
As I mentioned, after dragon player creates the video surface, everythin should work normal.
It's possible that your patches and the nvidia graphics driver itself also contribute to this(but needs more testing with differend configs).
But in general, I need to watch out how to make the switch between the rendering outputs more smooth.
Thanks for the logs so far :)

**Comment by ahjolinna** [comment]
@OpenProgger : those patches are old (for stable v0.29.1 build) and I'm currently using the latest vulkan beta driver (v418.49.04) ...oh and I dont have any conf enabled when i did the testing...I do have [huge script](https://github.com/ahjolinna/mpv-conf) conf for it (that I should update)

I dont know what distro u are using, but if you are using arch there is aur pkg for the same'ish  full version that I have been using 

https://aur.archlinux.org/packages/mpv-full-git
I do also use the [packman repo](http://packman.links2linux.org/) verison of ffmpeg ...for non-free codecs (and other features)
