### ISSUE TITLE
Unlike gnome-mpv (also using libmpv), phonon-mpv does not work with hwdec=vaapi and requires hwdec=vaapi-copy

### ISSUE THREAD

**Issue by kupiqu** [OpenProgger/phonon-mpv#6]
Please see https://github.com/mpv-player/mpv/issues/6584#issuecomment-480594278

This seems to discard an issue in libmpv because gnome-mpv (using libmpv) works fine.

**Comment by OpenProgger** [comment]
Post the debug log with non-working vaapi(with PHONON_BACKEND_DEBUG=3) and, if possible, a debug output from gnome-mpv with working vaapi.
Maybe they do something special with libmpv which make it work.

**Comment by kupiqu** [comment]
https://pastebin.com/5kFW6uUm

(Sorry, I have been a bit busy lately)

**Comment by kupiqu** [comment]
No idea how to get debug info from gnome-mpv, I just installed the deb package in ubuntu. I could get though the log from mpv, hope it helps:

[mpv.log](https://github.com/OpenProgger/phonon-mpv/files/3073815/mpv.log)

**Comment by OpenProgger** [comment]
Does this issue still persist in Plasma 6? There were some changes during the Qt6 port that could fix hwdec.

**Comment by OpenProgger** [comment]
Closed due to inactivity
