### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by jocrecre** [OpenProgger/phonon-mpv#9]
I have tried to build the project but an error raised, here is the log: 

jorge@bionic:/tmp/phonon-mpv/build$ cmake -DCMAKE_INSTALL_PREFIX=/usr ../src/
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:3 (add_definitions):
  Policy CMP0005 is not set: Preprocessor definition values are now escaped
  automatically.  Run "cmake --help-policy CMP0005" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:5 (if):
  if given arguments:

    "VERSION_GREATER" "4.9.50"

  Unknown arguments specified

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/tmp/phonon-mpv/build/CMakeFiles/CMakeOutput.log".

**Comment by OpenProgger** [comment]
Looks like some phonon variables are undefined. Maybe a phonon/libphonon-dev package is missing?
What distro are you using?

**Comment by jocrecre** [comment]
Here you are: 

sorry about the Spanish but  "ya está en su versión más reciente" means "the package is already installed using the latest available version"

jorge@bionic:/tmp/phonon-mpv/build$ uname -am
Linux bionic 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
jorge@bionic:/tmp/phonon-mpv/build$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
jorge@bionic:/tmp/phonon-mpv/build$ sudo apt-get install libphonon4 libphonon4qt5-4 phonon4qt5  libphonon-dev
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
libphonon-dev ya está en su versión más reciente (4:4.10.0-2).
libphonon4 ya está en su versión más reciente (4:4.10.0-2).
libphonon4qt5-4 ya está en su versión más reciente (4:4.10.0-2).
phonon4qt5 ya está en su versión más reciente (4:4.10.0-2).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 414 no actualizados.

**Comment by OpenProgger** [comment]
Ah now I see that you took the wrong source path. Instead of "../src/" just write ".." .

**Comment by jocrecre** [comment]
Thansk for the hint. 

Now I get another error, it seems related to the mpv version:

jorge@bionic:/tmp/phonon-mpv/build$ sudo apt-get install libmpv-dev mpv
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
libmpv-dev ya está en su versión más reciente (0.27.2-1ubuntu1).
mpv ya está en su versión más reciente (0.27.2-1ubuntu1).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 446 no actualizados.
jorge@bionic:/tmp/phonon-mpv/build$ 
jorge@bionic:/tmp/phonon-mpv/build$ 
jorge@bionic:/tmp/phonon-mpv/build$ 
jorge@bionic:/tmp/phonon-mpv/build$ 
jorge@bionic:/tmp/phonon-mpv/build$ cmake -DCMAKE_INSTALL_PREFIX=/usr ..
-- Using CMake automoc builtin
-- Found Phonon4Qt5: /usr/lib/x86_64-linux-gnu/cmake/phonon4qt5
-- Checking for module 'mpv>=1.101.0'
--   Requested 'mpv >= 1.101.0' but version of mpv is 1.25.0
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:15 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/tmp/phonon-mpv/build/CMakeFiles/CMakeOutput.log".

**Comment by OpenProgger** [comment]
As CMake reports, you have mpv 0.27.2 installed but this project requires at least 0.29.0 which provides the correct API version.

**Comment by jocrecre** [comment]
You were right, the message " 'mpv >= 1.101.0' but version of mpv is 1.25.0" was annoying me.  

In order to get the mpv annd libmpv 0.29 in ubuntu 18 this is needed: 

sudo add-apt-repository ppa:mc3man/bionic-media
sudo apt-get install libmpv-dev mpv

And then it got compiled successfully

**Comment by OpenProgger** [comment]
Since the issue is fixed.
Closed
